In [1]:
import pandas as pd
import os
os.chdir("D:/Term-2/MachineLearning/ASS-2")

In [2]:
beauty  = pd.read_json("Beauty_5.json",lines=True)

In [3]:
beauty.head()

,asin,helpful,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,7806397051,"[3, 4]",1,Very oily and creamy. Not at all what I expect...,"01 30, 2014",A1YJEY40YUW4SE,Andrea,Don't waste your money,1391040000
1,7806397051,"[1, 1]",3,This palette was a decent price and I was look...,"04 18, 2014",A60XNB876KYML,Jessica H.,OK Palette!,1397779200
2,7806397051,"[0, 1]",4,The texture of this concealer pallet is fantas...,"09 6, 2013",A3G6XNM240RMWA,Karen,great quality,1378425600
3,7806397051,"[2, 2]",2,I really can't tell what exactly this thing is...,"12 8, 2013",A1PQFP6SAJ6D80,Norah,Do not work on my face,1386460800
4,7806397051,"[0, 0]",3,"It was a little smaller than I expected, but t...","10 19, 2013",A38FVHZTNQ271F,Nova Amor,It's okay.,1382140800

In [8]:
ratings=pd.read_csv("ratings_Beauty.csv",header=None)
ratings.columns= ['reviewerID','asin','rating','unixReviewTime']
ratings=ratings.drop(['unixReviewTime'],axis=1)
ratings.head()

       reviewerID        asin  rating
0  A39HTATAQ9V7YF  0205616461     5.0
1  A3JM6GV9MNOF9X  0558925278     3.0
2  A1Z513UWSAAO0F  0558925278     5.0
3  A1WMRR494NWEWV  0733001998     4.0
4  A3IAAVS479H7M7  0737104473     1.0

In [27]:
ratings[ratings.reviewerID=='A1YJEY40YUW4SE']

             reviewerID        asin  rating  unixReviewTime
340      A1YJEY40YUW4SE  7806397051     1.0      1391040000
440062   A1YJEY40YUW4SE  B000V6BCSW     2.0      1391040000
807482   A1YJEY40YUW4SE  B0020YLEYK     5.0      1328140800
942164   A1YJEY40YUW4SE  B002WLWX82     1.0      1391040000
1177542  A1YJEY40YUW4SE  B004756YJA     5.0      1318896000
1337973  A1YJEY40YUW4SE  B004ZT0SSG     5.0      1318896000
1538217  A1YJEY40YUW4SE  B006XL55FK     5.0      1391040000
1982381  A1YJEY40YUW4SE  B00GZTXTZI     4.0      1391040000

In [14]:
beauty_rating = pd.merge(beauty,ratings,on=['asin','reviewerID'])

In [15]:
beauty_rating.head()

,asin,helpful,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime,rating
0,7806397051,"[3, 4]",1,Very oily and creamy. Not at all what I expect...,"01 30, 2014",A1YJEY40YUW4SE,Andrea,Don't waste your money,1391040000,1.0
1,7806397051,"[1, 1]",3,This palette was a decent price and I was look...,"04 18, 2014",A60XNB876KYML,Jessica H.,OK Palette!,1397779200,3.0
2,7806397051,"[0, 1]",4,The texture of this concealer pallet is fantas...,"09 6, 2013",A3G6XNM240RMWA,Karen,great quality,1378425600,4.0
3,7806397051,"[2, 2]",2,I really can't tell what exactly this thing is...,"12 8, 2013",A1PQFP6SAJ6D80,Norah,Do not work on my face,1386460800,2.0
4,7806397051,"[0, 0]",3,"It was a little smaller than I expected, but t...","10 19, 2013",A38FVHZTNQ271F,Nova Amor,It's okay.,1382140800,3.0

In [25]:
beauty_pivot = beauty_rating.pivot("asin",'reviewerID','rating').fillna(0)

In [26]:
beauty_pivot.head()

reviewerID,A00414041RD0BXM6WK0GX,A00473363TJ8YSZ3YAGG9,A00700212KB3K0MVESPIY,A0078719IR14X3NNUG0F,A01198201H0E3GHV2Z17I,A02155413BVL8D0G7X6DN,A02849582PREZYNEI31CV,A029527620Q3SK5XW16RR,A03236882LUP4ARMDDMXU,A03364251DGXSGA9PSR99,...,AZYNK58DULI59,AZYVVBYSD74KP,AZZ5ASC403N74,AZZ91VNEU3XYX,AZZIOU48NE8PC,AZZNK89PXD006,AZZQXL8VDCFTV,AZZT1ERHBSNQ8,AZZU6NXB8YJN9,AZZZLM1E5JJ8C
asin,,,,,,,,,,,,,,,,,,,,,
7806397051,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9759091062,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9788072216,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9790790961,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9790794231,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

In [29]:
beauty_matrix = csr_matrix(beauty_pivot.values)
beauty_matrix

<12101x22363 sparse matrix of type '<class 'numpy.float64'>'
	with 198502 stored elements in Compressed Sparse Row format>

In [30]:
model_knn =NearestNeighbors(metric = 'cosine',algorithm = 'brute')

In [31]:
model_knn.fit(beauty_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [33]:
distance,indicies = model_knn.kneighbors(beauty_pivot.iloc[0,:].reshape(1,-1),n_neighbors=6)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.

In [36]:
beauty_pivot.index[indicies]

Index([['7806397051', 'B003UHKJ5G', 'B00021KD2C', 'B0035LT8WM', 'B003ATNYJC', 'B007RX3AFA']], dtype='object', name='asin')